atomic-7.1-cloud.ks
atomic-7.1-vagrant.ks
atomic-7.1.tdl
build_ostree_components.sh

Pushing back the changes needed to get this running from an automated script in ci.centos.org.

Downstream

---

tests/vagrant-libvirt.sh
tests/vagrant-test.sh

at the moment, just running vagrant-libvirt.sh should give you a working vagrant environ on the machine, then init the vagrant libvirt box and run a few commands on there.

add a stub of tests to run the libvirt box, and check it can container

---

centos-ci/setup/roles/rdgo-system/tasks/main.yml

I'm really about to set up an rdgo for "infrastructure" like rdgo
here.

ci/setup: Install latest rpmdistro-gitoverlay manually

---

overlay.yml

overlay: Add Kubernetes

---

build_stage1.sh

implement static delta as discussed in #95 
I tested this in the ci, seems to work.

implement static deltas

---

build_stage1.sh

due to https://github.com/projectatomic/rpm-ostree/commit/17fb9802a1185797f55eb49c49f16ac3a9cc2c5a

use older rpm-ostree for now

---

centos-ci/jjb/sig-atomic.yml

See https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2016-July/msg00030.html

ci: Add a job to build centosmin

---

overlay.yml

http://pkgs.fedoraproject.org/cgit/rpms/libtasn1.git/commit/?h=f24&id=4802fcbdd83bfbfd6d37474e65363e2ff615c163

overlay: Pull in Fedora libtasn1

---

overlay.yml

Might as well start doing builds from git master for this too.

overlay: Add rpm-ostree-toolbox

---

README.md

So maybe some day someone other than me will do it.

README.md: Describe how to do CBS builds here

---

centos-ci/run-image-cloud
vagrant.ks

Adapt the existing ks, tweak our cloud image generation.

ci: Add Vagrant image

---

centos-ci/setup/roles/rdgo-system/tasks/main.yml

It really needs symbol versioning.

setup: Bring in the latest libsolv

---

centos-ci/jjb/sig-atomic.yml
centos-ci/libtask.sh
centos-ci/libtoolbox.sh
cloud.ks

This involved reworking things to be a bit more generic in some cases.

ci: Generate images for alpha

---

overlay.yml

Now that micro-yuminst bundles it:
https://github.com/cgwalters/micro-yuminst/commit/669f4541aa700f76c9205b43f4e0efd3ff69042e

overlay: Drop libhif again

---

centos-ci/run-treecompose

Maybe this should be in `do-release-tag`...but this is easy for now.

treecompose: Generate a delta for alpha

---

CentOS-extras.repo

extras.repo: Exclude atomic, to ensure we get CAHC version

---

centos-ci/jjb/sig-atomic.yml

ci: Prune docker base images

---

build_stage1.sh

Since people building this for the first time won't have one.

stage1: Only generate a static delta if we have a previous commit

---

build_stage2.sh
pxelive.ks

Based on 44fcc824076782befaeece5736bc94974e4acb25 from master branch.

add pxelive build step

---

releases.yml

Again part of the principle of making Alpha sane-ish to run.

releases: Cut a new release (specifically to pull in "Dirty COW" fix)

---

CentOS-CR.repo

these excludes from the CR repo allowed my test compose to complete

temp fix for issue 178

---

centos-atomic-host.json
centos-atomic-vagrant.ks
centos-atomic.ks
config.ini

* merge bootstrap pkgs into main packages list
* add mutate-os-release
* remove kubernetes master pkgs
* stop removing gpu drivers
* remove additional logo files
* add gomtree pkg

sync metadata w/ upstream 7.3

---

releases.yml

This is mostly 7.3 content, except for docker and selinux-policy.
That should be sorted out soon.

releases: New alpha

---

centos-ci/run-treecompose

treecompose: Use ostree-releng-scripts version of rsync

---

overlay.yml

Should fix current treecompose.

overlay: Build gomtree and dependencies

---

vagrant.ks

Until we have package layering in Anaconda.  This solves
some bootstrap problems; see
https://github.com/dustymabe/vagrant-sshfs/issues/63
https://github.com/openshift/openshift-ansible-contrib/pull/132
Note I didn't actually test this via a full anaconda kickstart run, I
just copy/pasted the `%post` section into a root shell.

vagrant: Hack in sshfs

---

vagrant.ks

I was doing some more testing, some tweaks follow.

vagrant: Followup fixes for sshfs

---

centos-ci/setup/roles/rdgo-system/tasks/main.yml

Yeah, sorry.  But I want our CI/build system to work so we can debug
other things.

ci: Fold and make selinux permissive until Docker builds get sorted

---

centos-ci/setup/roles/rdgo-system/tasks/main.yml

This one appears to work in my testing now.

ci: Use updated docker, enable selinux again

---

centos-atomic-host-continuous.json

manifest: Update version prefix to 2017

---

releases.yml

This one should fix the SELinux issues.

releases: Another new alpha, with more functional docker

---

centos-ci/jjb/sig-atomic.yml
centos-ci/libtask.sh

Minor fixes to finally get the smoketest branch up and running

---

CentOS-extras.repo
virt7-docker-common-candidate.repo

Now that we're not building it anymore.

repos: Do include atomic from virt7-docker

---

centos-ci/jjb/sig-atomic.yml

Now that the smoketest job is chugging along, let's start creating cloud
images based on them.
Closes: #238

images: start producing from the smoketested branch

---

releases.yml

Time to cut a new version, it's been a month.

releases: Cut a new alpha (from current smoketested)

---

releases.yml

Rolls up the kernel CVE fix among other things.
Also I documented the process a bit better now.

releases: Cut a new alpha from smoketested

---

build_stage1.sh
centos-atomic-host.json

see https://github.com/CentOS/sig-atomic-buildscripts/pull/240#issuecomment-276769236
I tested this PR in the ci, the tree builds.
@jlebon

Revert temp fixes made in PRs 240 & 242

---

build_stage1.sh
centos-atomic-host.json

Reverts CentOS/sig-atomic-buildscripts#262
see https://github.com/CentOS/sig-atomic-buildscripts/pull/262#issuecomment-291665140

Revert "Revert temp fixes made in PRs 240 & 242"

---

build_sign.sh
build_stage1.sh

@kbsingh will this work w/ how you're doing the signing?

remove temp static delta fix, move to build_sign.sh

---

centos-atomic-host.json

see https://ci.centos.org/job/Atomic_Host_DownStream/296/consoleText

don't try to remove centos-logos

---

centos-atomic-host.json

finish removing centos-logos bit from remove-from-packages

---

centos-atomic-host.json

bump ver to 1711

---

centos-atomic-host.json

podman is in now-released rhelah 7.5.1, so adding it here

add podman

---

centos-ci/run-rdgo-rsync
centos-ci/run-treecompose

Missed this when following up with Colin's suggestion in #351.

ci: Also chmod regular files, not just dirs

---

nightly_run.sh

add nightly script
