CentOS-Base.repo, CentOS-updates.repo, centos-7.tdl, centos-atomic-7.tdl, centos-atomic-base.json, centos-atomic-host-7.ks, centos-atomic-host-7.tdl, centos-atomic-host.json, config.ini
The following changes help make rpm-ostree-toolbox be able work
with this git repository.  With -toolbox, you can create custom
atomic trees, disk images, and installer media.
* CentOS-Base.repo
- toolbox can only handle one repo description per file
* CentOS-updates.repo
- Addition of the updates repo
* centos-7.tdl
- generic centos7 TDL for building a utility image
* centos-atomic-base.json
- Added updates repo
- corrected error for missing comma in repos list
- remove extlinux, use grub2
* centos-atomic-cloud-docker-host.json
- renamed to centos-atomic-host.json which -toolbox will
automatically detect.
* centos-atomic-host-7.ks
- kickstart needed by imagefactory during disk creations
* centos-atomic-host-7.tdl
- atomic TDL file needed by imagefactory during disk creations
* config.ini …
=> Update Git Repo for rpm-ostree-toolbox

centos-atomic-base.json
This ensures we get xfs for example.
See https://github.com/cgwalters/rpm-ostree/commits/3a41c65c8a654837364d8d72ebf61f229dc18954
=> manifest: Force initramfs to be host-independent

centos-atomic-host.json, cloud7-testing.repo
This, it turns out, was a bug.  We got a newer than desired cloud-init
package due to an error in koji tagging.  Now that we've fixed it, the
cloud repo is no longer required and should be removed to avoid
unexpectedly pulling in packages outside of our core atomic/virt tags
=> remove cloud repo reference

centos-atomic-base-devel.json, centos-atomic-host-devel.json
Ideally, once we have content in stable tags in the CBS we should
modify the "non-devel" JSON to use repos based on the content of
those tags.
For now, simply having these devel JSON files should allow us to
more confidently make day to day changes in the host definition
without worrying about breaking users attempting to atomic upgrade
on the existing released images.
=> add development definitions in preparation for stable release

centos-atomic-host.json
It's now obsoleted by kubernetes.
=> manifest: Remove cadvisor

centos-atomic-host.json
When Ian did the original metadata export, he dropped
subscription-manager from the tree manifest, presumably under the idea
that it's not necessary for CentOS.
That's true on the face of it - but there are subtle side effects.
For example, subscription-manager presently depends on a tiny bit of
the yum Python library.
The RHELAH upstream removed `/usr/bin/yum`, but kept
`/usr/lib/python2.7/site-packages/yum` for this reason.
Now, it turns out further that some utilities like Ansible do `import yum`:
https://github.com/ansible/ansible-modules-core/blob/devel/packaging/os/yum.py
That module actually calls out to *both* `/usr/bin/yum` and directly
invokes the Python library depending on what it's doing.
But the bottom line is that due to circumstance, Ansible rules like:
```
- name: Install …
```
=> manifest: Add subscription-manager to ensure higher fidelity

virt7-testing.repo
This is documented in `man yum.conf`.  I'm specifically making this
change because libhif doesn't parse spaces, so we fail to do the
exclude, and thus pull in the virt7 upstream kernel, which we don't
want.
=> virt7-testing: Use space separated list

centos-atomic-host.json, group, passwd
Extracted from internal, while still preserving the s/redhat/centos/
parts.
=> downstream: Update metadata for 7.1.2

build_ostree_components.sh
We want to reproduce the upstream versioning, so people understand
they're using a rebuild of which specific version.
=> Add a version

rhel-atomic-rebuild.repo
We're pulling in the wrong version (systemd-208-99) of systemd, from our [rhel-atomic-rebuild](http://buildlogs.centos.org/centos/7/atomic/x86_64/Packages/) repo. This PR excludes that systemd, allowing in the systemd from the core repos.
=> exclude systemd-208-99 from the cah repo

CentOS-CR.repo, centos-atomic-host.json
Add continuous release repo from centos, which provides new packages a bit earlier than the standard repos, for nightly build purposes.
=> Add Continuous Release repo

build_stage1.sh
This is a new(er) metadata file that allows enumerating branches, and
helps support metalinks and static delta GPG.  See:
https://git.gnome.org/browse/ostree/commit/?id=f8f5da219edd2279322bba916879fd53c2b65350
Closes #54
=> stage1: Generate an ostree summary file

atomic-7.1-cloud.ks
This adds the `GROWPART` change, which is really important
for ensuring cloud images expand to their rootfs size with modern
docker-storage-setup.
This replaces #60, but edits the correct file.
=> sync metadata from upstream

virt7-docker-common-candidate.repo
These RPMs are not GPG signed, so let's at least use `https://`
for transport integrity.
=> virt7-docker: Use https

atomic-centos-continuous.repo, centos-atomic-host-continuous.json
This treefile config pulls in the continuous rdgo builds.
=> atomic-host-continuous: Merge in config that pulls in rdgo

build_stage1.sh
#71 merged in a new treefile to include rdgo pkgs in the devel build, but the existing treefile is hardcoded into the build script. This PR makes the treefile configurable via an env variable, with the value defaulting to the existing treefile if $TreeFile is unset.
=> make treefile in build stage 1 configurable

centos-ci/run-build
To avoid leaking content into the build directory.
=> centos-ci/run-build: Use absolute tmpdirs

overlay.yml
These are hooks available for use with newer versions of Docker.
=> overlay: Add oci-systemd-hook, oci-register-machine

centos-ci/jjb/sig-atomic.yml
For some reason it was picking downstream in my job.
=> ci: Explicitly build master branch

build_stage1.sh
Otherwise we may end up losing history if we `rsync --delete`.
=> build: Sync full previous tree

overlay.yml
Fixed skopeo.spec in Fedora's dist git. Hopefully that should address the failure seen in https://github.com/projectatomic/skopeo/issues/80
@cgwalters PTAL
EDIT: not ready, i686 failures in koji...
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> overlay.yml: unfreeze skopeo

centos-ci/setup/roles/rdgo-system/tasks/main.yml
Otherwise we error out if it's already new enough.
=> ci/setup: s,install,upgrade, for manual yum invocation

centos-atomic-host-continuous.json, overlay.yml
We really need to distinguish this from the CentOS Core, since it's
quite different.
=> overlay: Add the -devel release package

overlay.yml
```
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/libexec/rpm-ostreed
31 metadata, 38 content objects fetched; 83813 KiB transferred in 1 seconds
Copying /etc changes: 31 modified, 8 removed, 46 added
Transaction complete; bootconfig swap: yes deployment count change: 0
Freed objects: 107.9 MB
Changed:
selinux-policy 3.13.1-60.el7_2.3 -> 3.13.1-61.atomic.0.el7.centos
selinux-policy-targeted 3.13.1-60.el7_2.3 -> 3.13.1-61.atomic.0.el7.centos
...
-rwxr-xr-x. root root system_u:object_r:install_exec_t:s0 /usr/libexec/rpm-ostreed
```
=> overlay: Add backported selinux policy

centos-atomic-host.json
These are new dependencies of rpm-ostree package layering:
https://github.com/projectatomic/rpm-ostree/pull/338
Now in practice it *would* be better for these to be added to the
fedora rpm-ostree spec file, but I don't yet want to hard depend on
these in Fedora - the implementation may change.
=> manifest: Add bubblewrap and fuse

overlay.yml
=> overlay: Freeze oci-systemd-hook dist-git

overlay.yml
The dist-git gained the golang backport patch which we don't need.
=> overlay: Unfreeze oci-systemd-hook, drop patches for skopeo

atomic-centos-continuous.repo
We want e.g. our skopeo whose `git describe` returns something older
than `1.9` to win out.
=> atomic-centos-continuous.repo: Add a priority to ensure we override

centos-atomic-host.json, virt7-docker-el-candidate.repo
First, I haven't really been maintaining the atomic7 repo since manual
integration is too painful.
I'll probably put rpm-ostree into EPEL at some point instead.
We're rebuilding everything here, so let's just drop it.
Second and more notably, drop virt7-docker-common-candidate since it's
broken right now (`docker-lvm-plugin` can't be installed).
This takes us down to the docker from the Core Extras rebuild, which
isn't very exciting, but in the big picture we really want to have
more control here over the version of Docker we build, and we want to
do CI/CD bits, which Koji/CBS doesn't let us do.
=> Drop CBS repos (virt7-docker-common-candidate and atomic7-testing)

overlay.yml
See:
https://gitlab.com/cgwalters/centosmin
https://gitlab.com/cgwalters/micro-yuminst
Adding this so it's easier to later start generating the docker image
in CentOS CI.
=> overlay: Add micro-yuminst (and readd libhif)

overlay.yml
This has a new `thin_ls` command which helps users estimate space
usage.
Rebuilding the Fedora version is easy and works.
=> overlay: Pull in a new device-mapper-persistent-data

overlay.yml
This actually breaks our CI right now because apparently gitlab just
hangs on `git fetch` after deleting a project.
=> overlay: Update for micro-yuminst transition to github

centos-ci/do-release-tags, centos-ci/run-build, centos-ci/setup/roles/rdgo-system/tasks/main.yml, releases.yml
Add a `releases.yml` file which is a delarative way to do
"ostree tags".  This adds a first release for an `alpha` branch.
In the future I plan to add image generation to this.
=> ci: Add a lightweight 'releases' promotion system

cloud/README.md
Basic info about cloud provider scripts (TK) and (mostly) TODOs.
=> add stub page for cloud provider scripts

centos-ci/jjb/sig-atomic-defaults.yml, centos-ci/jjb/sig-atomic.yml, centos-ci/libtask.sh, centos-ci/libtoolbox.sh, centos-ci/run-image-cloud, centos-ci/run-image-pxelive, centos-ci/run-installer, centos-ci/run-rdgo, centos-ci/run-rdgo-rsync, centos-ci/run-treecompose
Make the "execute script on Duffy node, gathering build logs" a
generic model that's used for everything.  This way we can more
cleanly have logs for failed installer builds for example (not
implemented yet).
Introduce a mechanism to propagate selected environment variables from
Jenkins to the node, which means that the tasks can reference
`$WORKSPACE` as a scratch area.  In the future I plan to also have
things like `${ref}` be parameterized, so that it's easier to
introduce image builds for stable tags.
=> ci: Dedup code in jobs

releases.yml
There are a number of changes, but the most important one is that we
pick up the addition of the remotes to the `-release` package, which
makes the alpha media installation have out-of-the-box upgrades.
(I didn't test the release process itself, let's see...)
=> releases: Update to alpha 2016.0.202

centos-ci/jjb/sig-atomic.yml
Now that the upstream repo does both.
=> ci: Introduce fedora-24 minimal image too

overlay.yml
This is needed for newer d_type by default, which will fix overlayfs.
https://bugzilla.redhat.com/show_bug.cgi?id=1288162#c8
=> overlay: Backport newer xfsprogs

centos-ci/setup/roles/rdgo-system/tasks/main.yml
Unfortunately glib2's lack of versioned symbols means we may hit
issues with `g_file_enumerator_iterate()` unless we update it.  Might
as well ensure ostree is updated too.
Really we should update everything...or switch to containers...but
for now, this.
=> main: Ensure we pull latest ostree + glib2

rhel-atomic-rebuild.repo
I manually dropped cockpit-ostree-0.114 from the rebuild repo
until the Extras build finishes.
=> rhel-atomic-rebuild: Use temporary workaround repo

overlay.yml
While runc isn't 1.0 yet, we might as well ensure we're version
locked with Fedora.
=> overlay: Bind runc with Fedora's version

centos-atomic-host-continuous.json
The version starting with `2016.` is rather uninformative, let's
switch to starting with `7.` being the major.  Also the intermediate
`0.` is pointless, so kill it.
Finally, use the new `mutate-os-release` field to ensure the
ostree version ends up in `/etc/os-release`.
=> manifest: Use 7. before version, drop 0, add mutate-os-release

overlay.yml
We want to use it in system containers.
=> overlay: Bump runc to v1.0pre

centos-ci/do-release-tags, centos-ci/run-treecompose, releases.yml
Previously, we were doing promotion based on updates to the branch
ref.  The problem with this is that we don't have in-repo knowledge of
the history of the target `alpha`. branch.  Things like `ostree log`
show the `continuous` branch.  And in particular, if we want to
generate static deltas between the promoted alpha commits, we'd have
to maintain a branch history of alpha.
So this reworks things to create a new commit, but with the *same
binary content* as the origin commit.  We add metadata `promotion-of`
into the alpha commits that allow us to trace the origin state, and
allows this tool in particular to implement idempotency.
This in turn will allow us to just blindly invoke `ostree static-delta
generate .../alpha` and have it work.
Closes: …
=> ci: Rework alpha to be based on recommit promotion

cloud.ks
Various discussion in https://bugzilla.redhat.com/show_bug.cgi?id=1193590
but it's easiest to stop waiting and just add the one liner hack.
This isn't a *complete* fix because:
1) This doesn't apply to ISO installs
2) It is an annoying bit of trivium that everyone else using rpm-ostree
will have to carry in their kickstarts
=> cloud.ks: Ensure root has a default bash prompt

overlay.yml
The goal here is that we version lock Fedora with CentOSDev, so
we can perform simultaneous integration testing.
=> overlay: Rebuild cockpit from Fedora

overlay.yml
This reverts commit 6eec6da3abe63feefe718819b391a142079616f9.
It fails `%check` with `--new-chroot`.
```
<petervo> they all look related to cockpit not able to find a inet device to listen on
<walters> petervo, mock --new-chroot which is nspawn
<walters> with --private-network which is just loopback
<petervo> yeah, that's why
```
=> Revert "overlay: Rebuild cockpit from Fedora"

overlay.yml
Our internal CI running against CAHC caught projectatomic/atomic#648
and it seems that part of the fix is going to require a version of
skopeo that is in the @mtrmac repo/branch.
This change (hopefully) changes CAHC to track that version of skopeo.
=> overlay: track skopeo signing work

CentOS-extras.repo
Followup to https://github.com/CentOS/sig-atomic-buildscripts/pull/155
=> Exclude skopeo from CentOS extras to ensure we get it from rdgo

virt7-docker-el-candidate.repo
It was excluded from CentOS-Extras in #157, but then it got pulled
from virt7-docker-el-candidate.  So exclude it there, too.
Another follow-up to #155
=> Exclude skopeo from virt7-docker

centos-atomic-host.json
This package contains the FIPS dracut module, which is required for AH
to properly function when booted in FIPS mode.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1377226
=> manifest: add dracut-fips to enable FIPS mode

centos-atomic-host.json
The 'attr' package was getting pulled in by the 'glusterfs-fuse'
package in Centos Atomic Host.  Because CAHC has dropped that from the
package list, we lost the package and the ability to use `getfattr` in
the [atomic-host-tests.](https://github.com/projectatomic/atomic-host-tests)
=> manifest: explicitly include attr package

centos-atomic-host.json
This reverts commit a383b9c794c53c2fc616bcf91df5a193bfc65f36.
=> Revert "manifest: add dracut-fips to enable FIPS mode (#160)"

releases.yml
Things seem OK-ish, and we really need to pick up
security updates.
=> releases.yml: Cut a new release from 7.2016.412

centos-ci/run-treecompose
Things actually break now since apparently we gc'd the old
alpha commits :/
Anyways, we don't need the `--ignore-no-previous-promotion`, and
we can now reliably use `^` to refer to the previous ref.
=> treecompose: Drop legacy code paths for previous alpha model

overlay.yml
Add a version of dracut and cpio that have --reproducible so that the
initramfs doesn't change on each commit.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> overlay.yml: add dracut and cpio with --reproducible

vagrant.ks
Right now, in the downstream box, we're able to use
config.ssh.username = 'root'
to tell Vagrant to directly ssh into root. This is great when e.g.
scripting things that assume root access without having to pepper sudo
everywhere.
Let's be consistent and do the same here so that they can be used
interchangeably in a Vagrantfile.
=> vagrant.ks: set up rootpw like downstream

vagrant.ks
As a follow-up to 909489b, we also need to explicitly unlock the root
account in %post, to undo the locking done in the inherited cloud
kickstart. In downstream, this is not an issue because the vagrant
kickstart does not inherit from the cloud kickstart.
=> vagrant.ks: also make sure the root account is unlocked

overlay.yml
The features that were coming from the previous branch are now in git
master, so we should be able to start tracking it again.
=> overlay: have skopeo track git master again

centos-atomic-host.json
It's long since been folded into `packages`.  I'm dropping the
`filesystem` dependency out since that's what we're doing in Fedora.
=> manifest: Stop using `bootstrap-packages`

centos-atomic-host.json, cloud.ks
Nothing big here, but we do pick up the `mutate-os-release` change.
=> Sync metadata with downstream

centos-ci/run-treecompose
This reverts commit 59514d596787cce25b977025fff2f00b778a88cb.
Sadly the CentOS version of rsync doesn't know about
`--ignore-missing-args`.  The fix will likely be to rework it to use
Fedora or backport rsync or something.
=> Revert "treecompose: Use ostree-releng-scripts version of rsync (#185)"

atomic7-testing.repo
The compose started pulling `atomic` from `atomic7-testing` which
has an ancient version of the RPM.  We want to test it from git
master, so just exclude it.
FWIW, I didn't test locally, so I'm hoping no other repos take precedence for this RPM.
Fixes #188
=> exclude 'atomic' from atomic7-testing.repo

centos-ci/setup/roles/rdgo-system/tasks/main.yml
Building the cloud image via `rpm-ostree-toolbox` has been failing for
a while and the root cause appears to be a missing `libgsystem`
dependency (see projectatomic/rpm-ostree-toolbox#104).
I think this should get `rpm-ostree-toolbox` working again.
Fixes #193
=> rdgo-system: install libgsystem

releases.yml
In light of both the latest alpha and continuous releases having
SELinux issues (see:
https://github.com/CentOS/sig-atomic-buildscripts/issues/191), let's put
alpha to the latest known working release (7.2016.1024 is right before
the sepolicies started regressing).
---
It might look strange for versions to go backwards, but since ostree doesn't care about version strings, it shouldn't cause any upgradability issues.
=> releases.yml: backtrack alpha to a known working version

cloud.ks, vagrant.ks
This should fix the `network` service being enabled in the Vagrant box,
otherwise it's mostly reordering and other small tweaks.
See also https://pagure.io/fedora-kickstarts/pull-request/109
=> cloud/vagrant: Sync kickstarts with Fedora

centos-ci/setup/roles/rdgo-system/tasks/main.yml
This should hopefully get the systems working again.
(Really what I want is Atomic Host in Duffy, so we don't
have to assemble something that looks like AH in order to
build and test AH...)
=> ci: Use virt7-testing docker, drop toolbox hotfix

overlay.yml
This was carrying a bugfix for something we now have in the base 7.3
content.
=> overlay: Drop selinux-policy override

centos-atomic-host.json
It's not built yet, and isn't a critical dependency anyways.
=> host: Revert addition of `gomtree`

centos-atomic-host.json
It doesn't work yet because we don't have the new release package.
=> downstream: Drop mutate-os-release

centos-ci/setup/roles/rdgo-system/tasks/main.yml
The main systems should use a stable Docker, to build and test
systems that use a newer one.
Closes: https://github.com/CentOS/sig-atomic-buildscripts/issues/210
=> main: Drop back to Core docker

overlay.yml
We had a frozen git tag, and at that point we might as well track
Fedora.
=> overlay: Version lock runc with Fedora

centos-ci/setup/roles/rdgo-system/tasks/main.yml
Something changed (I think mock) to start pulling in python-distro, which
requires lsb, which blows up because we have `stub-redhat-lsb-only-for-ceph` in
the repos.
We should only need the content from atomic7-testing to *build* AH, not the
AH-specific content.
=> ci: Drop centos7-atomic repo from build systems

CentOS-extras.repo, virt7-docker-el-candidate.repo
It was reported to me that we had an old oci-systemd-hook, and
a newer one was desired for system container work.
=> repos: Ensure we pick up our oci-systemd-hook and oci-register-machine

CentOS-extras.repo, overlay.yml, virt7-docker-el-candidate.repo
It turns out docker has a Requires on oci-register-machine with
an Epoch, which ours doesn't include.  This causes libsolv to
depsolve back to an ancient 1.9 docker without it.
We really need to pull docker fully into rdgo to fix issues like
this.  Alternatively, we could teach rdgo to automatically pull
in the upstream Epoch.
In the meantime, this.
=> overlay: Nevermind, do manual integration for oci hooks

centos-atomic-host.json, virt7-docker-common-candidate.repo, virt7-docker-el-candidate.repo
This is what we recommend in https://wiki.centos.org/Cloud/Docker - the -el
version isn't being updated as often, and honestly it's all super confusing.
Closes: #220
=> Switch over to docker common

releases.yml
Fixes `docker run --privileged`.
=> releases: Cut a new alpha from 7.2017.6

centos-ci/jjb/sig-atomic-defaults.yml, centos-ci/jjb/sig-atomic.yml, centos-ci/libtask.sh, centos-ci/libtoolbox.sh, centos-ci/libvm.sh, centos-ci/run-rdgo, centos-ci/run-tree-smoketest, centos-ci/run-treecompose, centos-ci/setup/roles/rdgo-system/tasks/main.yml, centos-ci/utils/create-vm, centos-ci/utils/get-vm-ip, centos-ci/utils/sshwait
Add a new job, atomic-tree-smoketest-centos7, which runs after every new
tree compose. This job runs the improved sanity test from the
atomic-host-tests suite:
https://github.com/projectatomic/atomic-host-tests/tree/master/tests/improved-sanity-test
If the test passes, we bump the smoketested rev, which is stored on the
slave's home directory, for lack of a better place. Whenever the
treecompose runs, we pick up the rev and insert it in releases.yaml so
that do-release-tags does the needful.
Disclaimer: About 13.8% of this code is untested.
Resolves: https://github.com/CentOS/sig-atomic-buildscripts/issues/227
=> centos-ci: add smoketesting for the continuous branch

centos-ci/libvm.sh, centos-ci/run-tree-smoketest, centos-ci/setup/roles/rdgo-system/tasks/main.yml, centos-ci/utils/create-vm
I had initially tested this as the root user. We need just a few
modifications to make this work for builder.
=> run-tree-smoketest: adjust for builder user

centos-ci/jjb/sig-atomic.yml
This caused anything that relied on atomic-trigger-on-change to never
actually fire.
=> jjb: fix nested build-logs rsync'ing

centos-ci/jjb/sig-atomic.yml, centos-ci/run-treecompose
So that it can create the smoketested ref.
=> do-release-tags: use the new --autocreate

centos-ci/setup/roles/rdgo-system/tasks/main.yml
Jobs are failing because of this syntax issue:
```
{"failed": true, "item": "config_opts['plugin_conf']['tmpfs_enable'] =
True", "msg": "unsupported parameter for module: \"line"}
```
We don't need to quote that argument, ansible will still be able to see
spaces in the `{{ item }}`.
I'm still confused though as to how this wasn't causing issues until
now, seeing as this line has been there for quite a while.
=> rdgo setup playbook: fix syntax issue

overlay.yml
I'm not sure what fell over exactly, but what we're trying to do
here (rebuild golang + libraries + components) on C7 without much
assistance from the upstream maintainers is a bit doomed in the long
term without more investment.
We will still pick up things like `etcd/kube/gomtree/skopeo` etc.
from the downstream rebuild + virt7 manual integration pool.
Yeah, this somewhat diminishes the value of CAHC but it's better
than not building.
Closes: #244
=> overlay: Stop rebuilding all golang bits

centos-atomic-host.json
temporarily necessary due to https://github.com/CentOS/sig-atomic-buildscripts/pull/240#issuecomment-276769236
=> revving version number for new release

centos-ci/run-treecompose
Now that the new ostree supports it and is built in atomic7-testing, let's use
it.
Closes: https://github.com/CentOS/sig-atomic-buildscripts/issues/186
=> ci/treecompose: Don't prune alpha

build_stage1.sh
temp fix for issue #259 
@cgwalters @kbsingh
=> temp fix for issue 259

atomic7-testing.repo
I realized that we did not encounter ostreedev/ostree#814 on CAHC,
which was odd because we should be building `ostree` from source.  The
latest CAHC composes seem to be pulling `ostree` from the
`atomic7-testing`, so let's just exclude it from the repo.
=> Exclude 'ostree' + 'rpm-ostree' from atomic7-testing repo

centos-ci/run-treecompose
For more rationale, see https://github.com/CentOS/sig-atomic-buildscripts/issues/269
I also switched over the pruning to use `5` for smoketested depth instead of
infinite, since I can't think of a use case for going far back.
I didn't test this locally.
Closes: https://github.com/CentOS/sig-atomic-buildscripts/issues/269
=> ci/treecompose: Redirect /alpha → /smoketested

releases.yml
Closes: https://github.com/CentOS/sig-atomic-buildscripts/issues/271
=> releases.yml: Follow up for alpha -> smoketested redirection

overlay.yml
See https://github.com/ostreedev/ostree/issues/867
=> overlay: Freeze ostree before /var generator handling

overlay.yml
This reverts commit b5387031cde604b46a6f12031131c7c386ceb393.
Should be fixed upstream now.
=> Revert "overlay: Freeze ostree before /var generator handling (#274)"

overlay.yml
Let's freeze `rpm-ostree` until projectatomic/rpm-ostree#862 is fixed.
=> Freeze rpm-ostree at 7b4134c8e6dc852d3a37fad7f47f33fce9c84bfd

build_stage1.sh
running into issues on mirror.centos.org and msync.centos.org where some content is not usable when downstream mirrors use different uid/ for pull and serve. just making the content public should fix that.
=>  ensure content is usable on mirrors and rsync targets

overlay.yml
In projectatomic/bubblewrap#205, the issue that we were seeing with
`bubblewrap` (projectatomic/bubblewrap#101) was fixed.  As such, we
can thaw out `bubblewrap` and continue to track git master.
=> overlay: Thaw bubblewrap 🔥

centos-ci/setup/roles/rdgo-system/tasks/main.yml
The `atomic*` jobs on ci.centos.org have been failing since Sept 1
because the duffy nodes have not been able to be setup successfully.
The failure was happening when trying to install all the required
packages in one shot, which caused a newer version of `librepo` to be
pulled in from the `atomic7-testing` repo.
But `python-librepo` requires an older version, so we just separate
the 'offending' packages (`libgsystem`, `rpm-ostree`,
`rpm-ostree-toolbox`) into a separate operation.
=> centos-ci:  separate 'yum install' operation into two steps

centos-ci/run-tree-smoketest
We abandoned the `alpha` branch in favor of the `smoketested` branch
(see #270), but the process of running the smoketest has been using
an ancient alpha image for months now.  Building an alpha image
appears to have been broken, so I'm not sure why we continue to try
to test against it.  Additionally, the smoketest has changed
so that we don't need to deploy HEAD-1 before running the test.
=> centos-ci: run the smoketest against continuous branch

centos-ci/jjb/sig-atomic.yml
The `alpha` branch is just a redirect to `smoketested` (see #270), so
let's stop building any artifacts on the `alpha` branch.
=> centos-ci: stop building any alpha artifacts

overlay.yml
Drop out lots of things that should be in 7.4 now.  Our dracut
changes aren't but...oh well.
Should fix: https://github.com/CentOS/sig-atomic-buildscripts/issues/299
=> overlay: Drop out a bunch of stuff (mostly in 7.4 now)

overlay.yml
This reverts commit 3227febf9980bc5eef387e9a3738b9a0e82accd0.
We should be able to build rpm-ostree now.
=> Revert "overlay: Drop rpm-ostree temporarily (#301)"

centos-ci/libtoolbox.sh
The 'atomic-cahc-image-cloud-smoketested' job[1] was failing because it
was expecting a directory named
`/centos-continuous/images-smoketested/cloud` during the `rsync` of
the final artifacts.  This directory was never created as part of the
image building process.
This change should allow the image building process to work with any
non 'continuous' branches going forward.
[1] https://ci.centos.org/job/atomic-cahc-image-cloud-smoketested/1150/console
=> centos-ci: handle non 'continuous' branches

centos-ci/run-tree-smoketest
In c46bbcf, the `run-tree-smoketest` script was changed to accommodate
the new way of running the a-h-t sanity test.
Unfortunately, this was a bit overzealous, as the HEAD commit is used
later in the script to record which commit was tested.
This change alters the script to pull the commit ID of HEAD, so that
it can be stored again as part of the logs.
=> centos-ci: retain the head commit

centos-atomic-host.json, virt7-container-common-candidate.repo
While debugging a `docker` issue on CAHC, we were informed that the
`virt7-docker-common-candidate` repo is no longer being used.  The new
repo is `virt7-container-common-candidate`, so we should start using
that.
=> repos: start using virt7-container-common-candidate

virt7-container-common-candidate.repo
In #307, we started using the `virt7-container-common-candidate` repo
to pull in a new version of `docker`.  Unfortunately, we've seen some
problems, some of which are affecting our tests:
projectatomic/docker#285
projectatomic/docker#286
Until we get fixes for those issues, let's stop grabbing `docker` from
the `virt7-container-common-candidate`.  This should cause `docker` to
come from the `CentOS-extras` repo.
=> repos: exclude `docker` from `virt7-container-common-candidate`

centos-ci/jjb/sig-atomic.yml, centos-ci/libtoolbox.sh
This is follow-up to #296. We were doing:
cd images/${imgtype}
which is OK in the continuous case, but in the smoketested case, the
correct dir is `images-smoketested`. This should hopefully make the
smoketested image builder work again.
Also do a few minor tweaks like using `--if-exists` and dropping the
need to specify `--disable-static-deltas`, which should have been long
fixed.
=> libtoolbox.sh: fix cd to nonexistent dir

centos-atomic-host.json
This is necessary for Meltdown+Spectre, and is included in RHEL AH.
Note that this required a patch to `microcode_ctl`:
https://git.centos.org/commit/rpms!microcode_ctl.git/4a0bea212733f7f139c327f7999d24e5eaacfab7
=> host: Add microcode_ctl

centos-ci/run-image-cloud
This should make it easier to debug failures like:
https://github.com/CentOS/sig-atomic-buildscripts/issues/333
=> cloud: Archive install screenshots on failure

centos-ci/run-image-cloud
We're hitting issues right now with the installer erroring out. To rule
out whether this is an `ENOSPC` issue, let's try bumping the installer
memory to 3G. If that works, then we can change this override in
rpm-ostree-toolbox (which currently forces it to 2G if it was less), or
make it configurable.
=> cloud: Bump libvirt memory to 3G

centos-ci/run-image-cloud
Minor follow-up to previous commit (#337). The default config ships with the
`memory` config commented out, so our sed wasn't doing anything.
=> cloud: Throw more sed at the ENOSPC issue

treecompose-post.sh
Follow in the footsteps of Fedora on this[1] and disable in the tree so
that upgrades to the tree don't suddenly have it enabled. But one can
enable it manually if wanted.
[1] https://pagure.io/atomic-wg/issue/372
Closes: #342
=> treecompose-post.sh: disable firewalld in tree

centos-7-and-extras-x86_64.cfg, overlay.yml
We need a newer distgit to pick up
https://src.fedoraproject.org/rpms/rpm-ostree/c/8e5fd5e7d64c45f36146e13080544e74c02a2612?branch=master
However libsolv now needs ninja which we don't have.  Since the version
that's in 7.5 is new enough let's drop it again.
=> overlay: Bump distgit to f28, drop libsolv

cloud.ks
I was using the Fedora Anaconda to try to install CentOSAH, and
it fell over on this.  It turns out Anaconda in RHEL7 land completely
ignores nonexistent services, but newer versions correctly error.
I think we initially considered shipping rsyslog, then ended up
trying to make it a container before system containers existed.
Anyways, now package layering exists.
=> cloud.ks: Remove rsyslog

centos-ci/libtask.sh, centos-ci/run-rdgo, centos-ci/setup/roles/rdgo-system/tasks/main.yml
We need to do this because Python 3.  One step for making this
pipeline more like FAHC.
=> rdgo: Use assembler container

centos-ci/libtask.sh
=> ci/libtask: Sync with FAHC

centos-ci/run-rdgo-rsync, centos-ci/run-treecompose
Make sure all the artifacts we sync out are owned by the `sig-atomic`
user.
=> ci: Make sure to chown before syncing out

centos-ci/run-rdgo-rsync, centos-ci/run-treecompose
E.g. otherwise `rdgo/build/repodata/` is not visible.
=> ci: Make all artifact directories accessible to nginx

centos-ci/libtask.sh
Freeze on coreos-assembler:alpha tag and sync `run_assembler` command
with FAHC. Notably, the `--entrypoint ''` arg.
=> libtask: sync with FAHC

centos-ci/run-rdgo-rsync, centos-ci/run-treecompose
Either the symlink is broken and `chmod` will complain, or the symlink
works and points to within the root dir passed to `find` and so will be
caught anyway. (This then makes sure we also don't somehow `chmod` a
target outside the root dir we care about).
=> ci: Don't chmod symlinks

overlay.yml
See: https://github.com/dustymabe/ignition-dracut/pull/26#issuecomment-431496837
=> overlay.yml: Freeze ostree to prevent Ignition regression

overlay.yml
Updated Ignition with the right ordering is now in COPR.
This reverts commit 70c3b844c90fb56199212927baf362772518759f.
=> Revert "overlay.yml: Freeze ostree to prevent Ignition regression"
